cmd_drivers/gpu/arm/b_r26p0/mali_kbase_strings.o := /home/kevios12/kernel/stock/toolchain/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/gpu/arm/b_r26p0/.mali_kbase_strings.o.d -nostdinc -isystem /home/kevios12/kernel/stock/toolchain/bin/../lib/gcc/aarch64-linux-android/4.9.x-google/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -Werror -std=gnu89 -fno-PIE -DANDROID_VERSION=110000 -DANDROID_MAJOR_VERSION=r -mgeneral-regs-only -fno-pic -fno-asynchronous-unwind-tables -fno-pic -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os -Wno-maybe-uninitialized --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=4096 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -fno-inline-functions-called-once -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -DMALI_CUSTOMER_RELEASE=1 -DMALI_USE_CSF=0 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r26p0-01eac0"\" -DMALI_JIT_PRESSURE_LIMIT_BASE=1 -DMALI_INCREMENTAL_RENDERING=0 -DMALI_KBASE_PLATFORM_PATH=../.././drivers/gpu/arm/b_r26p0/platform/"exynos" -I./drivers/staging/android -DMALI_KBASE_BUILD -I./drivers/gpu/arm/b_r26p0 -I./drivers/gpu/arm/b_r26p0/platform_dummy -I./drivers/gpu/arm/b_r26p0/../../../base -I./include/linux -I./drivers/gpu/arm/b_r26p0/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_USE_CSF=0 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r26p0-01eac0"\" -DMALI_JIT_PRESSURE_LIMIT_BASE=1 -DMALI_INCREMENTAL_RENDERING=0 -DMALI_KBASE_PLATFORM_PATH=../.././drivers/gpu/arm/b_r26p0/platform/"exynos" -I./drivers/staging/android -DMALI_KBASE_BUILD -I./drivers/gpu/arm/b_r26p0 -I./drivers/gpu/arm/b_r26p0/platform_dummy -I./drivers/gpu/arm/b_r26p0/../../../base -I./include/linux -I./drivers/gpu/arm/b_r26p0 -I./drivers/gpu/arm/b_r26p0/debug -I./drivers/gpu/arm/b_r26p0/debug/backend -I./drivers/gpu/arm/b_r26p0/platform/exynos -I./drivers/gpu/arm/b_r26p0/backend/gpu    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(mali_kbase)" -c -o drivers/gpu/arm/b_r26p0/.tmp_mali_kbase_strings.o drivers/gpu/arm/b_r26p0/mali_kbase_strings.c

source_drivers/gpu/arm/b_r26p0/mali_kbase_strings.o := drivers/gpu/arm/b_r26p0/mali_kbase_strings.c

deps_drivers/gpu/arm/b_r26p0/mali_kbase_strings.o := \
  drivers/gpu/arm/b_r26p0/mali_kbase_strings.h \

drivers/gpu/arm/b_r26p0/mali_kbase_strings.o: $(deps_drivers/gpu/arm/b_r26p0/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/b_r26p0/mali_kbase_strings.o):
