dtb-y := \
	exynos7885-jackpotlte_eur_open_03.dtb \
	exynos7885-jackpotlte_eur_open_04.dtb \
	exynos7885-jackpotlte_eur_open_05.dtb \
	exynos7885-jackpotlte_eur_open_06.dtb \
	exynos7885-jackpotlte_eur_open_07.dtb \
	exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos7885-jackpot2lte_eur_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
        exynos7885.dtb

dtbo-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
        exynos7904-a40_eur_open_00.dtbo \
        exynos7904-a40_eur_open_01.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb* *.dtbo
