# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
	exynos/exynos7904-a40_eur_open_00.dtbo \
	exynos/exynos7904-a40_eur_open_01.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_GLOBAL) := \
	exynos/exynos7885-jackpotlte_dummy.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_GLOBAL) := \
	exynos/exynos7885-jackpot2lte_dummy.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_GLOBAL) := \
	exynos/exynos7885-jackpotlte_eur_open_03.dtb \
	exynos/exynos7885-jackpotlte_eur_open_04.dtb \
	exynos/exynos7885-jackpotlte_eur_open_05.dtb \
	exynos/exynos7885-jackpotlte_eur_open_06.dtb \
	exynos/exynos7885-jackpotlte_eur_open_07.dtb \
	exynos/exynos7885-jackpotlte_can_open_03.dtb \
	exynos/exynos7885-jackpotlte_can_open_04.dtb \
	exynos/exynos7885-jackpotlte_can_open_05.dtb \
	exynos/exynos7885-jackpotlte_can_open_06.dtb \
	exynos/exynos7885-jackpotlte_can_open_07.dtb \
	exynos/exynos7885-jackpotlte_kor_03.dtb \
	exynos/exynos7885-jackpotlte_kor_04.dtb \
	exynos/exynos7885-jackpotlte_kor_05.dtb \
	exynos/exynos7885-jackpotlte_kor_06.dtb \
	exynos/exynos7885-jackpotlte_kor_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_GLOBAL) := \
	exynos/exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
	exynos/exynos7885.dtb

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
