# SPDX-License-Identifier: GPL-2.0

dtbo-$(CONFIG_MACH_EXYNOS7885_A10_GLOBAL) := \
	exynos/exynos7884B-a10_eur_open_00.dtbo \
	exynos/exynos7884B-a10_eur_open_01.dtbo \
	exynos/exynos7884B-a10_kor_open_00.dtbo \
	exynos/exynos7884B-a10_kor_open_03.dtbo \
	exynos/exynos7884B-a10_kor_open_05.dtbo \
	exynos/exynos7884B-a10_sea_open_00.dtbo \
	exynos/exynos7884B-a10_swa_open_00.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A20_GLOBAL) := \
	exynos/exynos7884B-a20_cis_ser_00.dtbo \
	exynos/exynos7884B-a20_cis_ser_01.dtbo \
	exynos/exynos7884B-a20_cis_ser_03.dtbo \
	exynos/exynos7884B-a20_aus_xsa_00.dtbo \
	exynos/exynos7884B-a20_aus_xsa_01.dtbo \
	exynos/exynos7884B-a20_aus_xsa_03.dtbo \
	exynos/exynos7884B-a20_can_single_03.dtbo \
	exynos/exynos7884B-a20_can_single_05.dtbo \
	exynos/exynos7884B-a20_sea_xtc_00.dtbo \
	exynos/exynos7884B-a20_sea_xtc_01.dtbo \
	exynos/exynos7884B-a20_sea_xtc_03.dtbo \
	exynos/exynos7884B-a20_swa_open_00.dtbo \
	exynos/exynos7884B-a20_swa_open_01.dtbo \
	exynos/exynos7884B-a20_swa_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A20e_GLOBAL) := \
	exynos/exynos7884B-a20e_eur_open_00.dtbo \
	exynos/exynos7884B-a20e_eur_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
	exynos/exynos7904-a40_eur_open_00.dtbo \
	exynos/exynos7904-a40_eur_open_01.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A30s_GLOBAL) := \
	exynos/exynos7904-a30s_eur_open_00.dtbo \
	exynos/exynos7904-a30s_eur_open_01.dtbo \
	exynos/exynos7904-a30s_eur_open_02.dtbo \
	exynos/exynos7904-a30s_eur_open_03.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_A30_GLOBAL) := \
	exynos/exynos7904-a30_cis_open_00.dtbo \
	exynos/exynos7904-a30_cis_open_01.dtbo \
	exynos/exynos7904-a30_cis_open_02.dtbo \
	exynos/exynos7904-a30_swa_open_00.dtbo \
	exynos/exynos7904-a30_swa_open_01.dtbo \
	exynos/exynos7904-a30_swa_open_02.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_GLOBAL) := \
	exynos/exynos7885-jackpotlte_dummy.dtbo

dtbo-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_GLOBAL) := \
	exynos/exynos7885-jackpot2lte_dummy.dtbo

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOTLTE_GLOBAL) := \
	exynos/exynos7885-jackpotlte_eur_open_03.dtb \
	exynos/exynos7885-jackpotlte_eur_open_04.dtb \
	exynos/exynos7885-jackpotlte_eur_open_05.dtb \
	exynos/exynos7885-jackpotlte_eur_open_06.dtb \
	exynos/exynos7885-jackpotlte_eur_open_07.dtb \
	exynos/exynos7885-jackpotlte_can_open_03.dtb \
	exynos/exynos7885-jackpotlte_can_open_04.dtb \
	exynos/exynos7885-jackpotlte_can_open_05.dtb \
	exynos/exynos7885-jackpotlte_can_open_06.dtb \
	exynos/exynos7885-jackpotlte_can_open_07.dtb \
	exynos/exynos7885-jackpotlte_kor_03.dtb \
	exynos/exynos7885-jackpotlte_kor_04.dtb \
	exynos/exynos7885-jackpotlte_kor_05.dtb \
	exynos/exynos7885-jackpotlte_kor_06.dtb \
	exynos/exynos7885-jackpotlte_kor_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_JACKPOT2LTE_GLOBAL) := \
	exynos/exynos7885-jackpot2lte_eur_open_03.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_04.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_05.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_06.dtb \
	exynos/exynos7885-jackpot2lte_eur_open_07.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A40_GLOBAL) := \
	exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A30s_GLOBAL) := \
        exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A30_GLOBAL) := \
        exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A20e_GLOBAL) := \
        exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A20_GLOBAL) := \
        exynos/exynos7885.dtb

dtb-$(CONFIG_MACH_EXYNOS7885_A10_GLOBAL) := \
        exynos/exynos7885.dtb

always         := $(dtb-y) $(dtbo-y)
clean-files    := *.dtb *.dtbo
